DineConnect.Gateway/DineConnect.Gateway.Web/Controllers/BackOffice/BackOfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DineConect.Gateway.Web.Controllers.BackOffice
{
    [Authorize]
    public class BackOfficeController : Controller
    {
        public BackOfficeController()
        {
        }

        public ActionResult Index()
        {
            return View();
        }
     
    }
}

DineConnect.Gateway/DineConnect.Gateway.Web/Controllers/HomeController.cs
using System;
using DineConnect.Gateway.Application.Services;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DineConect.Gateway.Web.Controllers
{
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index()
        {
            ViewBag.Title = "DineConnect Gateway";
            return View();
        }

        public ActionResult Qb()
        {
            return View();
        }


        public ActionResult ZohoBooks()
        {
            return View();
        }
    }
}

DineConnect.Gateway/DineConnect.Gateway.Web/Views/Home/Index.cshtml
<style>
    textarea {
        width: 300px;
        height: 150px;
    }

    .col-md-12 {
        margin-top: 30px;
        border-bottom: 1px solid #ccc;
    }

    img {
        margin-top: 5px;
        margin-bottom: 5px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Connect Gateway</h1>
            <p>
                Complete Gateway for  <a href="http://dineconnect.net">DineConnect</a>
            </p>

        </div>

        <div class="col-md-6" >
            <h1></h1>
            <p>
                <a class="nav-link" href="@Url.Action("Index", "BackOffice")">BackEnd</a>
            </p>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>Xero Integration</h1>
            <img src="~/Content/images/xerogateway.png" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>QuickBooks Integration</h1>
            <img src="~/Content/images/qbgateway.png" />
        </div>
    </div>

</div>

DineConnect.Gateway/DineConnect.Gateway.Web/Views/Home/Notes.cshtml
<style>
    textarea {
        width: 300px;
        height: 150px;
    }

    .col-md-12 {
        margin-top: 30px;
        border-bottom: 1px solid #ccc;
    }

    img {
        margin-top: 5px;
        margin-bottom: 5px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Connect Gateway</h1>
            <p>Complete Gateway for  <a href="http://dineconnect.net">DineConnect</a></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>Xero Integration</h1>
            <img src="~/Content/dineXeroTenantGateway.png" />
        </div>
    </div>

</div>

DineConnect.Gateway/DineConnect.Gateway.Web/Views/Home/Qb.cshtml
@{
    ViewBag.Title = "Qb";
}

@section Scripts {
    <style>
        textarea {
            width: 300px;
            min-height: 170px;
        }

        .col-md-12 {
            margin-top: 30px;
            border-bottom: 1px solid #ccc;
        }

        img {
            margin-top: 5px;
            margin-bottom: 5px;
        }
    </style>
}

<h1>QuickBooks Integration</h1>

<div class="container">
    <div class="d-flex flex-column">

        <div class="p-2">
            <h3>Flow</h3>
            <img src="~/Content/qbAuthorizationFlow.png" />

        </div>

        <div class="p-2">
            <h2>1) Create a QuickBooks app</h2>
            <p>Open a intuit developer account and create an app from the link <a href="https://developer.intuit.com/app/developer/dashboard" target="_blank">https://developer.intuit.com/app/developer/dashboard</a></p>
        </div>

        <div class="p-2">
            <h2>2) Set the QuickBooks App</h2>
            <p>Note the ClientId and Secret, and set the Redirect url to gateway url plus <strong>/callback/quickbooks</strong>. For example: <strong>https://dcgateway.azurewebsites.net/callback/quickbooks</strong></p>

            <img src="~/Content/qb-app-settings.png" />
        </div>

        <div class="p-2">
            <h2>3) Set the Web.configs.</h2>
        </div>

        <div class="p-2">
            <strong>3.1) In the Gateway web.config, just set Qb Client and Secret.</strong>

            <textarea class="form-control" style="min-width: 100%" readonly>
            <add key="QuickBooksClientId" value="ABOFoqLgfwWiHKDmAGqxeEhadbvWUGtkPJXW3bMxaRC7fQrdlE" />



            <add key="QuickBooksClientSecret" value="WBARJiYgAev5KmZrDXWJUQ2MkzQ8xKDNipg6nBIV" />



            </textarea>
        </div>

        <div class="p-2">
            <strong>3.2) In the DineConnect web.config, set client_id and secret, plus the QuickBooks API Base.</strong>

            <div class="alert alert-info" role="alert">
                Intuit provides two kind of API endpoints. Those are <strong>production</strong> and <strong>sandbox</strong>. For development purposes, you can use sandbox endpoint.
                Sandbox endpoint provides sample data to play with, and you don't have to deal with business rules.
            </div>

            <textarea class="form-control" style="min-width: 100%" readonly>
                <add key="QuickBooksClientId" value="ABOFoqLgfwWiHKDmAGqxeEhadbvWUGtkPJXW3bMxaRC7fQrdlE" />
                <add key="QuickBooksClientSecret" value="WBARJiYgAev5KmZrDXWJUQ2MkzQ8xKDNipg6nBIV" />
                <!-- <add key="QuickBooksAPIBase" value="https://quickbooks.api.intuit.com"/> --> <!-- Production --> 
                <add key="QuickBooksAPIBase" value="https://sandbox-quickbooks.api.intuit.com" /> <!-- SandBox -->
            </textarea>

            <strong>Here is sample contacts provided by Sandbox endpoint</strong>
            <img src="~/Content/qb-sample-contacts.png" />

        </div>

        <div class="p-2">
            <img src="~/Content/qb-item-crud-note.png" />
        </div>

        <div class="p-2">
            <h2>Further reads</h2>
            <a href="https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/account" target="_blank">QuickBooks Account Reference</a> <br />
            <a href="https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/customer" target="_blank">QuickBooks Customer Reference</a><br />
            <a href="https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/invoice" target="_blank">QuickBooks Invoice Reference</a><br />
            <a href="https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/item" target="_blank">QuickBooks Item Reference</a>

        </div>
    </div>




</div>

DineConnect.Gateway/DineConnect.Gateway.Web/Views/Home/ZohoBooks.cshtml
@{
    ViewBag.Title = "ZohoBooks";
}

@section Scripts {
    <style>
        textarea {
            width: 300px;
            min-height: 170px;
        }

        .col-md-12 {
            margin-top: 30px;
            border-bottom: 1px solid #ccc;
        }

        img {
            margin-top: 5px;
            margin-bottom: 5px;
        }
    </style>
}

<h1>ZohoBooks Integration</h1>

<div class="container">
    <div class="d-flex flex-column">

        <div class="p-2">
            <h3>Flow</h3>
            <img src="~/Content/images/zohoBooksAuthorizationFlow.png" />

        </div>

        <div class="p-2">
            <h2>1) Create a Zoho app</h2>
            <p>
                Register for a developer account here: <a href="https://www.zoho.com/developer/">https://www.zoho.com/developer/</a>
            </p>


            <p>Navigate to ZOHO API Console <a href="https://api-console.zoho.com/" target="_blank">https://api-console.zoho.com/</a> and create a Zoho app. Select Server-based-application.</p>
            <img src="~/Content/images/create-zohapp.png" />

        </div>

        <div class="p-2">
            <h2>2) Set the QuickBooks App</h2>
            <p>Note the ClientId and Secret, and set the Redirect url to gateway url plus <strong>/callback/zohobooks</strong>. For example: <strong>https://dcgateway.azurewebsites.net/callback/zohobooks</strong></p>
            <img src="~/Content/images/redirect-uri-zoho.png" />
        </div>

        <div class="p-2">
            <h2>3) Set the Web.configs.</h2>
        </div>

        <div class="p-2">
            <strong>3.1) In the Gateway web.config, just set Zoho Client and Secret.</strong>

            <textarea class="form-control" style="min-width: 100%" readonly>
            <add key="ZohoBooksClientId" value="1000.VDH0X6JMH79DS2IYP8J2X87BHTOXNG" />

            <add key="ZohoBooksClientSecret" value="70e0ce9a43f8e9f2e54d41a145342bb26ee1a04f2a" />

            </textarea>
        </div>

        <div class="p-2">
            <strong>3.2) In the DineConnect web.config, set client_id and secret.</strong>

            <textarea class="form-control" style="min-width: 100%" readonly>
            <add key="ZohoBooksClientId" value="1000.VDH0X6JMH79DS2IYP8J2X87BHTOXNG" />



            <add key="ZohoBooksClientSecret" value="70e0ce9a43f8e9f2e54d41a145342bb26ee1a04f2a" />

            </textarea>

        </div>



        <div class="p-2">
            <p>Your client will pick the organization which he want to integrate with DineConnect.</p>
            <p>This will happen <strong>after</strong> authorization process, <strong>before</strong> navigating back to DineConnect.</p>
            <img src="~/Content/images/zohobooks-organization-selection.png" />
        </div>

        <div class="p-2">
            <h2>Further reads</h2>
            <a href="https://www.zoho.com/books/api/v3/#getting-started" target="_blank">ZohoBooks API Reference</a>
        

        </div>
    </div>




</div>